### PR TITLE
Restore N64 button colors

### PR DESCRIPTION
**Pull request by recardo-7**
Restore the original button colors from N64 instead of the current GC colors.
Based on [this list](https://pastebin.com/u628WqyU) by Roman.

### CODE REVIEW

**Comment by Yanis42** [comment]
can you put those changes under a define inside the config folder? (config_game.h maybe?), I think it would be nice if people could choose and not enforce the thing

otherwise that's a good thing to add :D

**Comment by recardo-7** [comment]
yeah at first I thought why would you want to use gc colors but it's always good to have an option. Added a define in config_game.h

**Review by Yanis42 — COMMENTED** [review]
code is ok to me but I haven't tried this (@ariahiro64)

**Comment by Trueffeloot** [comment]
@recardo-7 I noticed a few issues while testing

First issue is that the outlines of the cursor are still lighting green on equipment items or songs that require the A button to be pressed:
issue-cursor-outlines

Second issue is that the small box at the bottom of the inventory still has a green A button:
issue-inventory-text
issue-inventory-text2

This a button issue also applies to playing an ocarina song that includes the A Button:
image

Everything else should be good to go

**Review by ariahiro64 — CHANGES_REQUESTED** [review]
Colors should be 100% consistent before its merged.

**Comment by Yanis42** [comment]
I will be taking over this PR since recardo seems not available (and I'd like to merge this), gonna merge master and fix the issues with the pause menu

first time I'm doing this so hopefully it goes well lol

**Comment by Yanis42** [comment]
ok everything should be fixed now

**Comment by Trueffeloot** [comment]
@Yanis42 Seems good from what I can tell. The issues I reported are fixed. This is good to go and the A button in the pause menu can be fixed later 👍

**Review by Yanis42 — APPROVED** [review]

**Pull request merged**
