### PR TITLE
Add Widescreen toggle to SaveContext

### PR DESCRIPTION
**Pull request by Yanis42**
This isn't perfect yet, ideally we would keep the widescreen value outside of the current file but it's fine for now, I'd like to make that a fileselect option and this isn't the point of this change

### CODE REVIEW

**Comment by Trueffeloot** [comment]
the button check works.
but uhh
image
It seems like the skybox and other world textures get killed. I'm sure it's not me since I started from a fresh repo.

I have a deku stick on B?
image

If this is because of merging upstream/dev into widescreen_save, it should be fine, else this needs to be fixed

**Comment by Yanis42** [comment]
yeah dev has every pr, including the no sync one which causes those issues

though the stick on B is weird, probably some issue in z_sram.c

**Comment by Trueffeloot** [comment]
in that case, should be fine to be merged since it's anways targeting the dev branch

**Comment by Yanis42** [comment]
the equips should be fixed now

**Pull request merged**
