### PR TITLE
fix pause screen from being occluded

### PR DESCRIPTION
**Pull request by ariahiro64**
just a simple check if ithe game is paused. that prevents so may bugs with occlusion planes.

### CODE REVIEW

**Comment by Yanis42** [comment]
(make sure to run ``format.py``)

**Comment by ariahiro64** [comment]
did it anyway bit it is complaining about things that werent even my fault lol

**Comment by Yanis42** [comment]
you need to use clang-format-14 iirc

**Comment by ariahiro64** [comment]
fedora doesnt have 14

**Comment by ariahiro64** [comment]
this kind of sucks because such a small thing is now blocking me from contributing

**Comment by ariahiro64** [comment]
all checks pass now. thank distro box

**Review by Yanis42 — COMMENTED** [review]
it works but the side effect is it's not occluding at all once you pause, and it start occluding again when you unpause

I'm not sure if that's fine or not (@sauraen)

**Comment by sauraen** [comment]
This is okay and does solve this problem, but given that the occlusion plane also can cull the A button, I figured it was better to make a more comprehensive fix rather than just disabling it while paused: https://github.com/HackerN64/HackerOoT/pull/140

**Pull request closed without merging**
