### PR TITLE
Merge decomp/main in HackerOoT/Main

### PR DESCRIPTION
**Pull request by Yanis42**
it's been a while but I'm only merging the new changes

### CODE REVIEW

**Comment by ariahiro64** [comment]
having trouble testing this as it messes up n32 prs

**Comment by ariahiro64** [comment]
UPDATE tharo is updating his branch in a few

**Comment by Yanis42** [comment]
I merged the new commits, compiles on my machine™

**Comment by Yanis42** [comment]
closing, I wanna keep the old build system in a branch

**Pull request closed without merging**
