### PR TITLE
No syncs in texture setup commands

### PR DESCRIPTION
**Pull request by Yanis42**
Made by @sauraen, everything seems fine on emu (this should save render time, estimated by Sauraen at 2-5%)

### CODE REVIEW

**Comment by sauraen** [comment]
If this is just the patch file I put up in Discord, it *generally* works on console but there are a few issues where adjustments were needed (i.e. there are corruptions so syncs need to be manually added or "upgraded" from load to pipe syncs).

Testing this on HLE will be useless--it will ignore syncs. Many LLE emulators may also ignore the syncs.

**Comment by Yanis42** [comment]
yeah I basically made a branch, applied the patch you sent and opened the PR after testing if it worked, I'm gonna try on N64 and Wii VC to see what happens

**Comment by Yanis42** [comment]
Tested on Dolphin and a real N64, here's the results: https://imgur.com/a/MGcQeXE

Skybox and scenes (?) seems broken on N64 (with map select), on Wii VC (Dolphin) the pause menu background is the only issue

**Comment by sauraen** [comment]
That was roughly my experience too. Also, charging a spin attack hangs on N64.

When the contents of a texture (like independent of where it is on the screen) are corrupted, such as the skybox, it's likely somewhere there was a manual load sync added which should have been a pipe sync.

When there is flickering graphics, it's likely there is somewhere where currently there's no sync (because it was removed from the texture loading) which needs a pipe sync.

**Comment by Yanis42** [comment]
turns out there's a missing ``gDPLoadTLUTCmd``, which most likely causes all of the issues I experienced with this (skybox and pause menu map are fixed when adding the command back)

**Comment by Yanis42** [comment]
N64 (and most likely Wii VC) still has issues but on emu it's working properly, since I don't have a loader with an usb port I can't try easily on N64 to see what's wrong

**Comment by Yanis42** [comment]
This PR now targets the dev branch (which already have most of the changes from the original PR), I think we can merge this and fix the hardware issues later and add a comment to say it's broken on N64 (and probably Wii VC)

**Comment by sauraen** [comment]
The whole point of this is to make the game go faster on N64. Please don't make HackerOoT just become permanently broken on real hardware.

**Comment by Yanis42** [comment]
I know it's not ideal but I don't have the tools to debug on a real N64 currently so it would be a temporary "solution" until we finally have a fix, also the dev branch is the perfect place for such things since it's not intended to be stable in the first place

**Comment by Yanis42** [comment]
(also I want to keep HackerOoT working on real hardware as a Wii VC enjoyer, I think people should play on real hardware when they can because it gives a better experience imo)

**Comment by sauraen** [comment]
Okay, well, the current changes in this PR against develop are minimal and an improvement, so they're fine.

I'm a little concerned that nobody is ever going to take the time to debug a bunch of different issues to merge develop back to master.

**Comment by Yanis42** [comment]
the master branch is gonna become a release-only branch so we'll make sure everything works perfectly well when we want to merge dev in master

also if no ones makes a fix I'll do it myself as soon as I can, but that won't happen for months probably

**Comment by ariahiro64** [comment]
i think it should be under a define even if enabled by default

**Comment by Yanis42** [comment]
it's gonna be annoying but I'm gonna ifdef this whole thing so we can merge this

**Comment by Yanis42** [comment]
ok, everything is ifdeffed now, I decided to make a new file for gbi.h, it was the easiest solution tbh

I also moved graphic stuff, including this, to a new file ``config_graphics.h``, should be ready to merge

**Review by ariahiro64 — APPROVED** [review]
seems like everything is able to be enabled.
we will need revisit this when f3cdex3 is ready but it im satisfied for now.

**Comment by Yanis42** [comment]
merging this tomorrow

**Comment by ariahiro64** [comment]
tommorow never came lol

**Comment by Yanis42** [comment]
Lmao I went to get some milk and never came back

**Pull request merged**
